name: Notify Parent Repo

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch event to parent
        run: |
          curl -X POST https://api.github.com/repos/NotWrench/WEB-TECH-2026/dispatches \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{"event_type":"update-submodule"}'